### ISSUE TITLE
Fix Codecov

### ISSUE THREAD

**Issue by omaralbeik** [omaralbeik/UserDefaultsStore#10]
The project has a **100%** test coverage, however codecov is not working for some reason 😭
If you have an idea how to fix it, your help is highly appriciated

**Comment by omaralbeik** [comment]
Calling the expert @pawurb, please help 😅

**Comment by pawurb** [comment]
@omaralbeik I'll try to have a look this weekend.

**Comment by omaralbeik** [comment]
Thank you @pawurb

**Comment by omaralbeik** [comment]
Any updates on this @pawurb 😅
