### ISSUE TITLE
Use hash value as key?

### ISSUE THREAD

**Issue by ddddxxx** [omaralbeik/UserDefaultsStore#23]
Looks dangerous.

> Hash values are not guaranteed to be equal across different executions of your program. Do not save hash values to use during a future execution.

**Comment by omaralbeik** [comment]
@ddddxxx Any suggestion to improve this is highly appreicated 😃

**Comment by fcapon** [comment]
Since Xcode 10, this library is no longer usable: https://github.com/apple/swift-evolution/blob/master/proposals/0206-hashable-enhancements.md
Even with Swift 4, because Xcode 10 comes with Swift 4.2 and has compatibility mode for Swift 4.

This issue should be reopened.

**Comment by omaralbeik** [comment]
Thanks for bringing this up again @fcapon :)
I removed the `Hashable` constraint in #30

**Comment by fcapon** [comment]
Thanks! 🤗
