### ISSUE TITLE
Misleading docs

### ISSUE THREAD

**Issue by mark-anders** [omaralbeik/UserDefaultsStore#34]
Based on the documentation in the  readme, I got the impression that a laptop owned by a user came from the laptop store. Meaning that what was serialized to the store was the key to the laptop and that when I retrieved a user, it would also retrieve the laptop from the store.

What's actually happening is that the laptop is serialized into the data for the user. So if I were to say that John owned a MacBook and then changed the description of the MacBook in the laptop store, when I retrieved john's record, I would get the updated Macbook data. Instead, I get whatever was serialized when I saved john to the user store.

Does this make sense? I think it would be good to be explicit about what's happening, because I was getting inconsistency errors based on what I thought the docs were implying.

**Comment by omaralbeik** [comment]
Thank you for your feedback @mark-anders 

I'll close this for now, however, feel free to open a pull request updating the README 🙂
