### ISSUE TITLE
Swift PM: cannot load package

### ISSUE THREAD

**Issue by kalavski** [omaralbeik/UserDefaultsStore#36]
Cannot load package by SPM:
I have used:

".package(url: "https://github.com/omaralbeik/UserDefaultsStore.git", from: "1.4.0")

I have gotten:
`error: dependency graph is unresolvable; found these conflicting requirements:

Dependencies:
    https://github.com/omaralbeik/UserDefaultsStore.git @ 1.4.0..<2.0.0`

**Comment by omaralbeik** [comment]
@kalavski Sorry for my late response here, I believe this has been fixed in *v1.4.2*, please give it a try and let me know if you face the problem again :)
