### ISSUE TITLE
iCloud support feature request

### ISSUE THREAD

**Issue by sverin** [omaralbeik/UserDefaultsStore#38]
Would it be possible to add support to use iCloud through NSUbiquitousKeyValueStore instead of UserDefault ?

**Comment by omaralbeik** [comment]
@sverin Sure!, I'll give it a try this weekend, or even better feel try to open a pull request and help me with it 😜

**Comment by omaralbeik** [comment]
After a quick research; it looks like [`NSUbiquitousKeyValueStore`](https://developer.apple.com/documentation/foundation/nsubiquitouskeyvaluestore) is not suitable for this library for the following reasons:

- Unlike [`UserDefaults`](https://developer.apple.com/documentation/foundation/userdefaults) there is no way to create multiple stores in the same app.
- You can’t save more than 1024 key-value pairs.
- A single key can’t be larger than 64 bytes using UTF-8 encoding.
- The combined key-value storage is 1 MB.
- A single key-value pair cannot exceed 1 MB in size.

**Comment by omaralbeik** [comment]
@sverin I'll close this for now, feel free to reopen if you have any further questions
